services:
  - type: web
    name: diagnostiq-ai
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev python3-pyaudio ffmpeg libasound2-dev
      pip install --no-cache-dir -r requirements.txt
    startCommand: python gradio_app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true